### ISSUE TITLE
App crashes after using reflutter

### ISSUE THREAD

**Issue by ajayi-george** [Impact-I/reFlutter#288]
After following the instructions in the README, I utilized uber-apk-signer to align and sign the APK. While the installation of the APK was successful, it promptly crashed upon attempting to open it on my Android device. 

I am curious as to the cause of this issue and what steps I should take to resolve it. Thank you.

The original apk file can be downloaded [here](https://download.apkcombo.com/com.scb.phone/SCB%20EASY_3.76.0_apkcombo.com.apk?ecp=Y29tLnNjYi5waG9uZS8zLjc2LjAvNzk0MC45YWQwNGFlNmNiZjhjYTIyMTFmYmVlZDhiMWFmNDYyZjY1Zjc4OTRjLmFwaw==&iat=1708429966&sig=97ffaed3ba76abf06314837d324b0e66&size=333941243&from=cf&version=latest&lang=en&fp=9628ca1cf8928099571bb61d8df736bd&ip=105.113.82.95)

**Comment by jayluxferro** [comment]
@ajayi-george 

The issue is not due to reFlutter. The app enforces other check for debug mode and root detection using root-beer. 

reFlutter doesn't guard against that. It just provides you with traffic interception capability and also the dump of memory addresses of classes and methods.

**Comment by nmdbilal** [comment]
Same issue after using reflutter (App crashes).

Firebase Crashlytics Error console =>
Fatal Exception: android.content.res.Resources$NotFoundException: File res/rN.xml from xml type font resource ID #0x7f090002
       at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1382)

 Caused by java.io.FileNotFoundException: res/rN.xml
       at android.content.res.AssetManager.nativeOpenXmlAsset(AssetManager.java)

I am using this package (flutter_root_detection: ^1.0.0) to check rooted. And I will check isEmulator, isFridaDetected & isMagiskDetected.
