### ISSUE TITLE
How to determine commit for my engine version  5a9b8af18beb469ff41df5434819fa49

### ISSUE THREAD

**Issue by jaoh** [Impact-I/reFlutter#299]
I got the following hash 5a9b8af18beb469ff41df5434819fa49 this hash is not part of  https://github.com/Impact-I/reFlutter/blob/main/enginehash.csv how can i build the engine and get the commit

**Comment by jayluxferro** [comment]
@jaoh , currently these are all the snapshot hashes: https://github.com/Impact-I/reFlutter/blob/fcc50e900ba0fc8b0ad1b7caa9d62358c32e6ec8/scripts/enginehash.tmp.csv


What you have there isn't one of them.

You can use https://github.com/Impact-I/reFlutter/blob/main/scripts/get_snapshot_hash.py to check the snapshot hash. 

https://github.com/Impact-I/reFlutter/tree/main/scripts#readme


There's also a custom build instruction: https://github.com/Impact-I/reFlutter#custom-build

If you try that it'll fail since it's not a valid engine hash

**Comment by jaoh** [comment]
I used   scripts/get_snapshot_hash.py on my  libapp.so and got 5a9b8af18beb469ff41df5434819fa49
I also used scripts/get_flutter_engine.py  on my libflutter so and got c2ec683c4ea8a58a32a74465cc05dafdf7778517

The table under  [I/reFlutter/blob/fcc50e900ba0fc8b0ad1b7caa9d62358c32e6ec8/scripts/enginehash.tmp.csv](https://github.com/Impact-I/reFlutter/blob/fcc50e900ba0fc8b0ad1b7caa9d62358c32e6ec8/scripts/enginehash.tmp.csv) dose not contain my snapshot hash so i have to build it my self but how do i determine the engine commit for the docker command  ?

**Comment by jaoh** [comment]
I ran 

sudo docker run -e WAIT=300 -e x64=0 -e arm=0 -e HASH_PATCH=5a9b8af18beb469ff41df5434819fa49 -e COMMIT=c2ec683c4ea8a58a32a74465cc05dafdf7778517 --rm -iv${PWD}:/t reflutter

which resuled in 

bash: 1: bash: src/build/install-build-deps-android.sh: not found

Is this a problem with the dockerfile or my system ?

**Comment by jayluxferro** [comment]
@jaoh 

Like I said earlier, it won't work because `5a9b8af18beb469ff41df5434819fa49` isn't a valid engine hash. There's no flutter version that has that hash.

**Comment by jaoh** [comment]
I dont understand what i did wrong 

I extracted the hash with the provided scripts did i pass the wrong so files ?

Is there an alternative way to get the correct hash values

Thanks for your help

**Comment by jayluxferro** [comment]
@jaoh ,

You can share the `libapp.so` and `libflutter.so` for me to check it out.
